# Generated by Django 6.0.7 on 2026-08-14 11:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharma_app', '0001_initial'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['retailer', '-bill_date'], name='purchase_retailer_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['retailer', 'supplier', '-bill_date'], name='purchase_supplier_date_idx'),
        ),
        migrations.AddIndex(
            model_name='purchase',
            index=models.Index(fields=['retailer', 'payment_status', '-bill_date'], name='purchase_status_date_idx'),
        ),
    ]
